# Generated by Django 6.1.1 on 2026-10-02 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BreakSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Например: «После 2 урока»', max_length=50, verbose_name='Название')),
                ('start', models.TimeField(verbose_name='Начало')),
                ('end', models.TimeField(verbose_name='Конец')),
                ('weekdays', models.CharField(default='0,1,2,3,4', help_text='Номера дней через запятую: 0 — Пн … 6 — Вс', max_length=20, verbose_name='Дни недели')),
            ],
            options={
                'verbose_name': 'Перемена',
                'verbose_name_plural': 'Расписание перемен',
                'ordering': ['start'],
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('artist', models.CharField(max_length=200, verbose_name='Исполнитель')),
                ('file', models.FileField(upload_to='tracks/%Y/%m/', verbose_name='Файл')),
                ('uploaded_by', models.CharField(max_length=100, verbose_name='Кто загрузил')),
                ('school_class', models.CharField(max_length=10, verbose_name='Класс')),
                ('status', models.CharField(choices=[('pending', 'На проверке'), ('approved', 'Одобрен'), ('rejected', 'Отклонён')], default='pending', max_length=10, verbose_name='Статус')),
                ('reject_reason', models.CharField(blank=True, max_length=200, verbose_name='Причина отказа')),
                ('plays', models.PositiveIntegerField(default=0, verbose_name='Прослушиваний в зале')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Загружен')),
            ],
            options={
                'verbose_name': 'Трек',
                'verbose_name_plural': 'Треки',
                'ordering': ['-created_at'],
            },
        ),
    ]
